version: 2
jobs:
  build_deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker info
      - run:
          name: docker build and push
          command: |
            make UPDATE_LATEST=false DOCKERHUB_USER=objectrocket WEAVE_VERSION=${CIRCLE_TAG} PUBLISH_WEAVEDB=false all publish
workflows:
  version: 2
  # runs on version tags
  test_build_deploy:
    jobs:
      - build_deploy:
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+-rc[0-9]+$/
            branches:
              ignore: /.*/
